import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

/**
 * The README is the storefront: it is what a stranger reads before deciding
 * whether this repo is worth an afternoon. Its most checkable promise is that
 * every file it names exists — a `cp` of a template that was deleted two
 * commits ago fails on the reader's first command, and nothing in `bun test`
 * would have caught it.
 *
 * The same check covers the shipped surface itself. **One** analytics config
 * template ships, and it is the one `bun run seed` generates against; a second
 * template that disagrees about who the subject brand is sends a forker down a
 * path whose numbers are wrong in a way they cannot see. `.gitignore`'s `!`
 * un-ignore rules are part of that surface: an exception for a file that no
 * longer exists is a rule nobody can satisfy.
 *
 * The extraction below is deliberately mechanical, and the count is asserted
 * before the paths are. An assertion over an empty set is this project's
 * favourite way to pass: a regex that silently stops matching would otherwise
 * turn this file into fifteen lines of green that check nothing.
 */

const ROOT = resolve(import.meta.dir, "..");
const README = await readFile(resolve(ROOT, "README.md"), "utf-8");

/**
 * Paths the README names on purpose that are *not* files in a fresh clone.
 * Every entry needs a reason, and every entry is asserted to still be mentioned
 * — an allowlist nobody prunes is how this check rots into a no-op.
 */
const NOT_A_TRACKED_FILE: Record<string, string> = {
  "analytics.config.json": "gitignored; the reader creates it by copying the template",
  "targets.json": "an example filename for TARGETS_FILE, written by the reader",
  "custom.json": "an example filename for ANALYTICS_CONFIG, written by the reader",
  "apps/web/src/routeTree.gen.ts": "generated by the Vite plugin; gitignored",
  "routeTree.gen.ts": "the same generated file, named without its directory",
};

/** Output filenames with a date or glob standing in for the real one. */
const PLACEHOLDER = /(DATE|YYYY|<|\*|\{)/;

function pathsMentionedInReadme(): string[] {
  // Strip URLs first, or `https://bun.sh` contributes a `//bun.sh` "file".
  const prose = README.replace(/https?:\/\/\S+/g, " ");
  const matches = prose.match(/[A-Za-z0-9._/-]+\.(json|csv|md|ts|tsx|yml|sh)\b/g) ?? [];
  return [...new Set(matches)].filter((p) => !PLACEHOLDER.test(p)).sort();
}

describe("every file the README names resolves", () => {
  const mentioned = pathsMentionedInReadme();

  test("the extraction finds a plausible number of paths", () => {
    // The floor guards the check itself. If the regex or the README shape
    // changes such that this drops to a handful, the per-path assertions below
    // are passing over almost nothing and this is the test that says so.
    expect(mentioned.length).toBeGreaterThanOrEqual(10);
    expect(mentioned).toContain("analytics.config.example.json");
    expect(mentioned).toContain("prompts/default.csv");
  });

  test("each path either exists on disk or is a documented non-file", async () => {
    // Prose refers to a file by its basename once the full path has been given
    // — "the two rows in `targets.ts`" — so a bare name resolves if the repo
    // tracks exactly that filename somewhere.
    const tracked = await gitLsFiles(".");
    const basenames = new Set(tracked.map((p) => p.split("/").pop()));

    const missing: string[] = [];
    for (const path of mentioned) {
      if (path in NOT_A_TRACKED_FILE) continue;
      if (await Bun.file(resolve(ROOT, path)).exists()) continue;
      if (!path.includes("/") && basenames.has(path)) continue;
      missing.push(path);
    }
    expect(missing).toEqual([]);
  });

  test("the documented non-files are all still mentioned", () => {
    // Prunes the allowlist: once the README stops naming one of these, the
    // entry has to go, so a future missing file cannot hide behind it.
    const unused = Object.keys(NOT_A_TRACKED_FILE).filter(
      (path) => !README.includes(path),
    );
    expect(unused).toEqual([]);
  });

  test("no path the README names is the deleted demo pair", () => {
    // The specific regression #5 closes, stated by name rather than inferred
    // from a file listing, so it survives any future rewrite of this file.
    expect(README).not.toContain("analytics.config.demo.json");
    expect(README).not.toContain("prompts/demo.csv");
  });
});

async function gitLsFiles(pattern: string): Promise<string[]> {
  const proc = Bun.spawn(["git", "ls-files", "--", pattern], { cwd: ROOT });
  const [out, code] = await Promise.all([
    new Response(proc.stdout).text(),
    proc.exited,
  ]);
  expect(code).toBe(0);
  return out.split("\n").filter(Boolean);
}

describe("exactly one analytics config template ships", () => {
  test("only analytics.config.example.json is tracked", async () => {
    // `git ls-files`, not a directory listing: the reader's own
    // analytics.config.json is gitignored and must not count as a template.
    expect(await gitLsFiles("analytics.config.*.json")).toEqual([
      "analytics.config.example.json",
    ]);
  });

  test("it describes the brand the seed corpus and the shipped prompts use", async () => {
    const config = await Bun.file(
      resolve(ROOT, "analytics.config.example.json"),
    ).json();
    const prompts = await readFile(resolve(ROOT, "prompts/default.csv"), "utf-8");

    expect(config.brand.name).toBe("Taskwell");
    expect(prompts).toContain("Taskwell");
    // Real competitor names stay — the competitive view is only legible with
    // them — and the synthetic flag is what discloses that the numbers attached
    // to those names are invented.
    expect(config.brand.knownCompetitors).toContain("Todoist");
    expect(config.synthetic).toBe(true);
  });

  test("its comment does not send the reader to a file that was deleted", async () => {
    // The template's own `_comment` is documentation too, and it is the copy a
    // reader sees *after* the README, with the terminal already open.
    const config = await Bun.file(
      resolve(ROOT, "analytics.config.example.json"),
    ).json();
    expect(config._comment).not.toContain("analytics.config.demo.json");
    expect(config._comment).toContain("prompts/default.csv");
  });

  test("only prompts/default.csv is tracked, and .gitignore un-ignores exactly it", async () => {
    expect(await gitLsFiles("prompts/*.csv")).toEqual(["prompts/default.csv"]);

    const gitignore = await readFile(resolve(ROOT, ".gitignore"), "utf-8");
    const unignored = gitignore
      .split("\n")
      .filter((line) => line.startsWith("!"))
      .map((line) => line.slice(1).trim());
    expect(unignored).toEqual(["prompts/default.csv"]);

    // A dangling exception is invisible until someone wonders why a file they
    // added is not showing up, so assert each one still names a real file.
    for (const path of unignored) {
      expect(await Bun.file(resolve(ROOT, path)).exists()).toBe(true);
    }
  });
});
